USE LegacyEcommerce;
GO

CREATE TABLE Categories(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(30) NOT NULL,
	Image NVARCHAR(200),
	Description NVARCHAR(100),
	Featured BIT DEFAULT 0,
	CreateAt DATETIME DEFAULT GETDATE()
);
GO