USE LegacyEcommerce;
GO

CREATE TABLE Products(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	CategoryId INT,
	Name NVARCHAR(20) NOT NULL,
	Image NVARCHAR(200),
	Description NVARCHAR(100),
	Price Decimal(10,1) NOT NULL,
	Featured BIT DEFAULT 0,
	CreateAt DATETIME DEFAULT GETDATE()
);
GO